### PR TITLE
Various bug fixes and enhancements

### PR DESCRIPTION
**Pull request by fcastilloec**
The notification had to ignore all exceptions, not just IOExceptions. Specially because a NullException is produced first before any IOExceptions can be produced.

### CODE REVIEW

**Comment by fcastilloec** [comment]
I've added another features to the pull request. You can check them out in each of the commit message.
Let me know if you agree with this and if you have any questions.

**Comment by michaelkourlas** [comment]
My working copy is quite different from what's in the repository at the moment, so I don't know if I'll be able to merge in these changes directly, but I'll see if I can get some of these fixes into the next release.

**Comment by fcastilloec** [comment]
I guess you can always just try to rebase this pull request so it'll be easier for merging. Git will do a great job at that and it's very easy to just implement the changes that way

**Comment by fcastilloec** [comment]
Added an additional bug fix that deals with deleting conversations

**Comment by michaelkourlas** [comment]
I can't merge most of these changes in directly, but I think I covered everything: 

* Added support for the SEND intent.
* Text box now selected on new conversations and when the SEND intent is received.
* The application now supports SMS messages with a length greater than 160 characters.
* The icon behaviour of action bar items is now fixed.
* Sent messages aren't saved directly, but the database update that follows only retrieves messages dated after the most recent message received.
* Database updates when the conversations activity is resumed only retrieve messages dated after the most recent message received.
* Database updates following GCM messages only retrieve messages dated after the most recent message received.
* The other bug fixes you submitted are no longer applicable due to major structural changes to the code base.

If there's anything I missed, please let me know.

**Pull request closed without merging**
