### PR TITLE
contribution

### PR DESCRIPTION
**Pull request by jeanfmartel**
Hello Michael,
Here are the modifications that I made to your very nice app:
- Fixed the escape character glitch when displaying " and ' characters. (Issue #38)
- Added the destination contact number hint in the text box when writing. (Maybe enhancement #31)
- Optimized some filtering function.  The modification to the markConversationAsRead() function has made the biggest improvement in loading a long conversation. (Issue #20)
- Implemented a message draft feature (Issue #33)

That's it for now.  There are a lot of .xml files included in the commit which I didn't know about.  I should have put them in the ignore list but it was too late when I realized (3 commits later).  I hope it's not a big deal.
Also, I am a bit old school and I'm used to the  "Bracket On A New Line" coding style.  So I changed some lines so I could understand the function more easily, but I forgot to undo the changes before the commit.  So some functions have the section opening bracket on a new line... sorry about that.

It's the first time I contribute with GitHub, not shure I did the pull request correctly.  If not, please advise.
Thanks for your app, happy to contribute!
Jean-François from Montréal.

### CODE REVIEW

**Comment by anarcat** [comment]
you will probably need to merge/rebase your branch here. i suspect that cleaning up your commits by squashing them in topical commits (e.g. one per issue) would make this easier to review. but i'm not the maintainer here.

**Comment by michaelkourlas** [comment]
I'll be looking at integrating some or all of these changes here in the 0.4.2 release.

**Comment by michaelkourlas** [comment]
Note that some of these changes (e.g. the one to fix https://github.com/michaelkourlas/voipms-sms-client/issues/38) are no longer necessary.

**Comment by michaelkourlas** [comment]
I'm not going to merge this in directly, but I've made a bunch of analogous optimizations and fixes. Some of these fixes, however, are no longer required (e.g. the escape character problem) because VoIP.ms has fixed them on their end.

**Pull request closed without merging**
