### PR TITLE
Notification can stay visible until dismissed

### PR DESCRIPTION
**Pull request by arykov**
Michael, currently notifications show up on the screen and disappear after a few seconds. I added an option for them to be shown until user's explicit dismissal. It is off by default.

### CODE REVIEW

**Comment by michaelkourlas** [comment]
As it is, notifications aren't automatically dismissed (unless you open the conversation view associated with that notification) so I'm not sure what problem you're trying to fix. `setOngoing` prevents a notification from being dismissed altogether by the user, which probably isn't what you want.

**Comment by arykov** [comment]
Currently popup with the message shows and then disappears within a few seconds. Notification indicator appears in the corner. In my experience some of the less tech savvy users never look at those. What my change achieves is that this popup stays on top of the screen until the user swipes it or clicks mark as read on it. I only tested it on Android 5.1. Experienced difficulties with notifications showing up on Android 6 and 7 in the emulator.

**Comment by arykov** [comment]
Are you accepting or rejecting or waiting to verify behavior?

**Comment by michaelkourlas** [comment]
The behaviour you describe is by design. Heads up notifications -- which is what I assume you're referring to -- only appear for a few seconds. It's normal to have to check the notification drawer for notifications.

**Comment by arykov** [comment]
Yes, we are indeed talking about heads up notifications that disappear into the drawer. And I fully understand it is normal behavior.
Are you open to adding an ability to make those notifications more intrusive(hang on top until dismissed) if the user chooses to do so(enables it in the settings)?

**Pull request closed without merging**
