### PR TITLE
Add a special method to mark all in a conversation as unread.

### PR DESCRIPTION
**Pull request by andre-d**
Noticed things were getting insanely slow the more messages I had in a conversation.  Massive performance boost in long conversations.

### CODE REVIEW

**Comment by andre-d** [comment]
Further fixes incoming in other pull requests

**Comment by andre-d** [comment]
Okay, I believe I am done, it runs pretty smooth now with a large number of conversations and messages.

**Comment by ASalvail** [comment]
Do you have an .apk? I'd love to use the update and Michael doesn't look like he will update until this summer.

**Comment by andre-d** [comment]
Sure, I will get an APK up shortly, it is not signed the same so you may have to uninstall the old apk before installing the new one then restore your database if you want your old messages.  Do you know how to do that?

**Comment by andre-d** [comment]
@ASalvail I have an APK here: https://github.com/andre-d/voipms-sms-client/releases/tag/speedup

I caution that I provide no support for that release, etc.  It contains all of the changes seen here: https://github.com/andre-d/voipms-sms-client/commits/changes and is signed DIFFERENT from the official voip.ms sms app so if you want to keep your SMS database you will need to back up the app data, uninstall, install the new apk then restore the app data with something like Titanium Backup.

**Comment by ASalvail** [comment]
Sweet, thanks a lot!

**Comment by ASalvail** [comment]
It works like a charm. I decided to rely on voip.ms to backup the messages (meaning, I didn't delete them). The speedup is really noticeable.
Thanks again!

**Comment by michaelkourlas** [comment]
Just wanted to let people know that I've seen this and I'll do my best to merge it this summer after my exams.

**Comment by michaelkourlas** [comment]
I've implemented something like this in the latest release.

**Pull request closed without merging**
